name: CI/CD

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python lint
        run: |
          pip install flake8
          flake8 server/djangoapp/views.py \
            --ignore=E302,E501,E231,E275,E722,W293,E203,E712,F401,F811,F841,W391

      - name: JS lint
        run: |
          npm install -g jshint
          jshint server/frontend/src/components/Dealers/Dealers.jsx
